name: Deploy Node.js Server to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.17.0'  # Change to your Node.js version

      - name: Install dependencies and build frontend
        run: |
          cd ui
          npm install
          npm run build --prod

      - name: Copy code to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/app"

      - name: Stop and start SQL container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop sql_container || true
            docker rm sql_container || true
            docker run -d --name sql_container -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=spring -e MYSQL_USER=rachitanil -e MYSQL_PASSWORD=root -p 3306:3306 mysql:latest

      - name: Stop and start Node.js server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pm2 stop app || true
            cd /home/ec2-user/app
            npm install
            pm2 start src/app.ts --name app